add support for cygwin

diff --git a/concourse-server/scripts/concourse b/concourse-server/scripts/concourse
--- a/concourse-server/scripts/concourse
+++ b/concourse-server/scripts/concourse
@@ -75,6 +75,9 @@ die () {
   exit 1
 }
 
+# Use the maximum available, or set MAX_FD != -1 to use that value.
+MAX_FD="maximum"
+
 # Get the name of the OS in case there is OS-specified configuration that needs
 # to occur. Variable values will generally correspond as follows:
 #
@@ -83,6 +86,27 @@ die () {
 # darwin  | OS X
 # linux   | CentOS
 OS=`uname -s | tr "[A-Z]" "[a-z]" | tr -d ' '`
+
+# OS specific support (must be 'true' or 'false').
+cygwin=false
+msys=false
+darwin=false
+case $OS in
+  cygwin* )
+  cygwin=true
+  ;;
+  darwin* )
+  darwin=true
+  ;;
+  mingw* )
+  msys=true
+  ;;
+esac
+
+# For Cygwin, ensure paths are in UNIX format before anything is touched.
+if $cygwin ; then
+  [ -n "$JAVA_HOME" ] && JAVA_HOME=`cygpath --unix "$JAVA_HOME"`
+fi
 
 # Ensure that this script operates from the application root directory
 cd "${0%/*}"
@@ -182,7 +206,67 @@ else
   location of your Java installation."
 fi
 
-# Print the usage message
+# Increase the maximum file descriptors if we can.
+if [ "$cygwin" = "false" -a "$darwin" = "false" ] ; then
+  MAX_FD_LIMIT=`ulimit -H -n`
+  if [ $? -eq 0 ] ; then
+    if [ "$MAX_FD" = "maximum" -o "$MAX_FD" = "max" ] ; then
+      MAX_FD="$MAX_FD_LIMIT"
+    fi
+    ulimit -n $MAX_FD
+    if [ $? -ne 0 ] ; then
+      warn "Could not set maximum file descriptor limit: $MAX_FD"
+    fi
+  else
+    warn "Could not query maximum file descriptor limit: $MAX_FD_LIMIT"
+  fi
+fi
+
+# For Cygwin, switch paths to Windows format before running java
+if $cygwin ; then
+  APP_HOME=`cygpath --path --mixed "$APP_HOME"`
+  CLASSPATH=`cygpath --path --mixed "$CLASSPATH"`
+
+  # We build the pattern for arguments to be converted via cygpath
+  ROOTDIRSRAW=`find -L / -maxdepth 1 -mindepth 1 -type d 2>/dev/null`
+  SEP=""
+  for dir in $ROOTDIRSRAW ; do
+    ROOTDIRS="$ROOTDIRS$SEP$dir"
+    SEP="|"
+  done
+  OURCYGPATTERN="(^($ROOTDIRS))"
+  # Add a user-defined pattern to the cygpath arguments
+  if [ "$GRADLE_CYGPATTERN" != "" ] ; then
+    OURCYGPATTERN="$OURCYGPATTERN|($GRADLE_CYGPATTERN)"
+  fi
+  # Now convert the arguments - kludge to limit ourselves to /bin/sh
+  i=0
+  for arg in "$@" ; do
+    CHECK=`echo "$arg"|egrep -c "$OURCYGPATTERN" -`
+    CHECK2=`echo "$arg"|egrep -c "^-"`                                 ### Determine if an option
+
+    if [ $CHECK -ne 0 ] && [ $CHECK2 -eq 0 ] ; then                    ### Added a condition
+      eval `echo args$i`=`cygpath --path --ignore --mixed "$arg"`
+    else
+      eval `echo args$i`="\"$arg\""
+    fi
+    i=$((i+1))
+  done
+  case $i in
+    (0) set -- ;;
+    (1) set -- "$args0" ;;
+    (2) set -- "$args0" "$args1" ;;
+    (3) set -- "$args0" "$args1" "$args2" ;;
+    (4) set -- "$args0" "$args1" "$args2" "$args3" ;;
+    (5) set -- "$args0" "$args1" "$args2" "$args3" "$args4" ;;
+    (6) set -- "$args0" "$args1" "$args2" "$args3" "$args4" "$args5" ;;
+    (7) set -- "$args0" "$args1" "$args2" "$args3" "$args4" "$args5" "$args6" ;;
+    (8) set -- "$args0" "$args1" "$args2" "$args3" "$args4" "$args5" "$args6" "$args7" ;;
+    (9) set -- "$args0" "$args1" "$args2" "$args3" "$args4" "$args5" "$args6" "$args7" "$args8" ;;
+  esac
+fi
+
+# Function to print the usage message
 usage(){
   cat <<< "Usage: $APP_HOME/bin/concourse [ console | start | stop | restart | status | threaddump | heapdump | version ]
 
